using BSOFT.Security.DataAccess.ModelConfigurations;
using BSOFT.Security.Models;
using JetBrains.Annotations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;

namespace BSOFT.Security.DataAccess
{
    public class DbSecurityContext : DbContext
    {
        public DbSecurityContext(DbContextOptions<DbSecurityContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Identidad de forma predeterminada -> "Id" INTEGER  GENERATED BY DEFAULT AS IDENTITY
            modelBuilder.ForNpgsqlUseIdentityColumns();

            //Serie -> "Id" SERIAL PRIMARY KEY
            modelBuilder.HasSequence<int>("tbl_company_Id_seq")
                .StartsAt(1000)
                .IncrementsBy(5);

            modelBuilder.Entity<tbl_company>()
                .Property(o => o.Id)
                .HasDefaultValueSql("nextval('\"tbl_company_Id_seq\"')");


            //Aplicar configuracion
            modelBuilder.ApplyConfiguration(new UserConfiguration());
            modelBuilder.ApplyConfiguration(new CompanyConfiguration());
        }

        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_company> tbl_company { get; set; }
    }
}
